### ISSUE TITLE
XML里面的元素JS需要调用它需要初始化

### ISSUE THREAD

**Issue by nodeSoya** [MrSoya/soya2d#10]
现在XML里面的元素需要做JS操作需要设置ID然后用findView来实现绑定，这样的话如果需要操作的元素多了findView也写的比较多，可否里面有某个属性可以直接映射到JS呢

**Comment by MrSoya** [comment]
good suggest。场景中已经有一个.map属性，可以直接获取你想要的节点。但是xml中必须设置id
