### ISSUE TITLE
soya2d官网无法访问

### ISSUE THREAD

**Issue by ragnaroks** [MrSoya/soya2d#13]
另外impexjs有无意向提供一个lite版，考虑到seo需要，仅提供“数据绑定/DOM操作/事件响应”

**Comment by MrSoya** [comment]
无法访问应该是域名解析出问题了，正在核查。impex的问题你不是应该发到impex的issue吗。。

**Comment by ragnaroks** [comment]
@MrSoya 
主要是之前需要一个精简版的vue，最好未压缩的min.js只有30k以下，想起来有个soya2d开发的mvvm，但是想不起来叫啥，结果发现soya2d打不开了，还好后来想起了有star，找到了。。。
不过impex也很大了，我又用jquery去了。。。

**Comment by MrSoya** [comment]
。。。。官网已恢复
