### ISSUE TITLE
按需的单个文件加载

### ISSUE THREAD

**Issue by nodeSoya** [MrSoya/soya2d#16]
引擎能不能提供单个资源的按需加载接口呢？也只监听这个资源加载成功后的回调。比如游戏里面的头像需要按需加载。但是现在我快速加载两个头像，执行了两次load.start。然后监听end的事件，有可能会出现只加载好一个的时候就触发了end事件，这样在没有加载好资源的end回调里面就可能报错

**Comment by MrSoya** [comment]
已开放soya2d.Loader(game)接口
