### ISSUE TITLE
soya2d.Sound 这个对象是如何使用的?

### ISSUE THREAD

**Issue by ragnaroks** [MrSoya/soya2d#2]
var StartScene_BGM=new soya2d.Sound();
StartScene_BGM.play()  的参数是什么?
调试发现play方法好像没有参数,音频参数是在new的时候就传入?
那么又如何传入音频参数?

**Comment by ragnaroks** [comment]
试用了一个下午,发现代码无法保存,而且代码编辑器只能使用第一次...
保存后再打开就这样了:
![qq 20151016193729](https://cloud.githubusercontent.com/assets/7598199/10540746/66143904-743d-11e5-93b8-d2e2cdc73ec5.png)
![qq 20151016193741](https://cloud.githubusercontent.com/assets/7598199/10540748/6c00e146-743d-11e5-8acc-b404b6b6d6f9.png)

**Comment by MrSoya** [comment]
声音对象不需要显式创建，你只要在资源列表那里添加资源，就类似图片，然后获取音频资源播放即可，
下面的代码是 
http://soya2d.com/examples/game-xshooter.php 的源码，可以参考一下

var music = game.soundManager.find('bgm');
if(music)music.loop(true).play().fade(0,.5,4000);

**Comment by ragnaroks** [comment]
原来是这么用的,之前没有看过源码
那个api手册很具有误导性...
这里的'bgm'指的是文件名的bgm.mp3还是ide里面那个标识?

另希望修复ide的错误

还有,能否这样使用?
var music = game.soundManager.find("http://xxx/xxx.mp3");

**Comment by MrSoya** [comment]
bgm就是一个模糊查找的标识，全名是bgm.mp3你也可以只写bg
目前无法加载网络资源
IDE的bug会在重构后修复，目前正在开发impex，IDE会基于这个进行重构
