### ISSUE TITLE
点击事件出不来

### ISSUE THREAD

**Issue by xv-chang** [MrSoya/soya2d#5]
![qq 20160112190215](https://cloud.githubusercontent.com/assets/14342463/12261909/1704470c-b95f-11e5-8d66-a9ada3ac2ace.png)

刚开始用正常，来回点了几次就这样了，然后接结束进程，重新打开还是这样。

**Comment by xv-chang** [comment]
这个窗口也是关闭不了的。

**Comment by MrSoya** [comment]
这个是测试版，新版正在开发中，很快上线
