### ISSUE TITLE
找到一个文本这边计算每行内容的问题

### ISSUE THREAD

**Issue by willove** [MrSoya/soya2d#8]
在有一大段包括\n换行的文本里，会有吞字的情况出现，我看了下源码，只显示了在src/text/Text.js11行的lineString = text.substr(currCharPos, charNum + 1 + j); 这边得到的lineString

反复试了很多遍，后来在138行 if(lineWidth > this.w) 这个判断之后 又加了一个下面的判断

```
if (currCharPos + lineString.length == l) {
    lines.push(lineString);
    currCharPos += lineString.length;
    break;
}
```

文本就齐了。。

**Comment by MrSoya** [comment]
不好意思，这么晚才回复。最近在忙soya2.0的事情，beta版本已经差不多了。这个月应该可以上。你说的这个问题我测试一下。多谢
